### ISSUE TITLE
Improving questions visibility with fairness recommendations

### ISSUE THREAD

**Issue by geoffroyO** [agora-gouv/agora-back#277]
Bonjour,

Après avoir utilisé l'app je me rends compte qu'il y a un gros problème de visibilité des questions posées par les citoyens. En effet il n'y a aucun système d'équité qui est fait entre les questions. J'entends par là qu'il serait bien qu'une question posée il y a 1 mois puisse se trouver au même niveau de visibilité qu'une question posée le jour même sur l'application. 

Il serait donc peut être intéressant de réfléchir à un système de recommandations des questions plus égalitaire. Qu'en pensez-vous ?

**Comment by thierrylee** [comment]
Bonjour,

Navré pour le retard de la réponse, je n'avais pas vu cette issue.
Nous travaillons sur des fonctionnalités pour donner plus de visibilité aux questions autres que le top 10 des plus populaires. Le tout est encore en phase de conception donc je ne peux malheureusement pas en parler davantage.

**Comment by thierrylee** [comment]
Bonjour,

Encore navré pour le retard de cette nouvelle réponse, nous avons fait une mise à jour de l'application pour tenter d'y répondre: https://github.com/agora-gouv/agora-app/releases/tag/1.3.0
;)
